
server:
  port: 8085   # API Gateway port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # ----------------------------
        # Organization-Service Route
        # ----------------------------
        - id: organization-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/organizations/**
        # ----------------------------
        # Role-Service Route
        # ----------------------------
        - id: role-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/roles/**
        # ----------------------------
        # Group-Service Route
        # ----------------------------
        - id: group-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/groups/**
        # ----------------------------
        # User-Service Route
        # ----------------------------
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/users/**

      #  Add Global CORS Configuration
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5000"   # Your frontend origin
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
